// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Database;

#nullable disable

namespace reservation_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710120418_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Reservation.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 7, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 1,
                            VisitorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 7, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 2,
                            VisitorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 7, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 1,
                            VisitorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 7, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 3,
                            VisitorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 7, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 2,
                            VisitorId = 5
                        });
                });

            modelBuilder.Entity("Reservation.Models.QRCodeToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("QRCodeTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Expiration = new DateTime(2025, 7, 10, 18, 4, 17, 482, DateTimeKind.Local).AddTicks(6642),
                            IsUsed = false,
                            Uuid = "06fa41e9-d7c0-444a-875d-af8a68827324"
                        },
                        new
                        {
                            Id = 2,
                            Expiration = new DateTime(2025, 7, 10, 19, 4, 17, 485, DateTimeKind.Local).AddTicks(41),
                            IsUsed = false,
                            Uuid = "46609920-7fd2-4433-842d-8998c64b2068"
                        },
                        new
                        {
                            Id = 3,
                            Expiration = new DateTime(2025, 7, 10, 13, 4, 17, 485, DateTimeKind.Local).AddTicks(85),
                            IsUsed = true,
                            Uuid = "76506013-fad6-450e-a7b3-8b3cc552f150"
                        },
                        new
                        {
                            Id = 4,
                            Expiration = new DateTime(2025, 7, 10, 16, 4, 17, 485, DateTimeKind.Local).AddTicks(90),
                            IsUsed = false,
                            Uuid = "e1878767-d27f-47a9-95b8-32e0a1ae70b0"
                        },
                        new
                        {
                            Id = 5,
                            Expiration = new DateTime(2025, 7, 10, 17, 4, 17, 485, DateTimeKind.Local).AddTicks(185),
                            IsUsed = false,
                            Uuid = "038cde52-06ce-4dd5-99d3-0bb7d1db64c1"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@entreprise.com",
                            Name = "Alice Accueil",
                            Role = "Agent d'accueil"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@entreprise.com",
                            Name = "Bob Collaborateur",
                            Role = "Personnel"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@entreprise.com",
                            Name = "Charlie IT",
                            Role = "Administrateur"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactStaffId = 1,
                            Email = "alexandre@example.com",
                            FirstName = "Alexandre",
                            LastName = "Lejunior",
                            Phone = "0123456789",
                            Status = "Enregistré",
                            VisitReason = "Rendez-vous"
                        },
                        new
                        {
                            Id = 2,
                            ContactStaffId = 2,
                            Email = "elodie@example.com",
                            FirstName = "Élodie",
                            LastName = "Martin",
                            Phone = "0987654321",
                            Status = "Enregistré",
                            VisitReason = "Livraison"
                        },
                        new
                        {
                            Id = 3,
                            ContactStaffId = 1,
                            Email = "paul@example.com",
                            FirstName = "Paul",
                            LastName = "Dupont",
                            Phone = "0147852369",
                            Status = "Enregistré",
                            VisitReason = "Autre"
                        },
                        new
                        {
                            Id = 4,
                            ContactStaffId = 3,
                            Email = "sophie@example.com",
                            FirstName = "Sophie",
                            LastName = "Durand",
                            Phone = "0172638495",
                            Status = "Enregistré",
                            VisitReason = "Rendez-vous"
                        },
                        new
                        {
                            Id = 5,
                            ContactStaffId = 2,
                            Email = "julien@example.com",
                            FirstName = "Julien",
                            LastName = "Moreau",
                            Phone = "0192837465",
                            Status = "Enregistré",
                            VisitReason = "Rendez-vous"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Appointment", b =>
                {
                    b.HasOne("Reservation.Models.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation.Models.Visitor", "Visitor")
                        .WithMany("Appointments")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Reservation.Models.Staff", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Reservation.Models.Visitor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
