// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Database;

#nullable disable

namespace reservation_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Reservation.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("StaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 7, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 1,
                            VisitorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 7, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 2,
                            VisitorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 7, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 1,
                            VisitorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 7, 12, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 3,
                            VisitorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 7, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffId = 2,
                            VisitorId = 5
                        });
                });

            modelBuilder.Entity("Reservation.Models.QRCodeToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("QRCodeTokens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Expiration = new DateTime(2025, 7, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false,
                            Uuid = "11111111-1111-1111-1111-111111111111"
                        },
                        new
                        {
                            Id = 2,
                            Expiration = new DateTime(2025, 7, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false,
                            Uuid = "22222222-2222-2222-2222-222222222222"
                        },
                        new
                        {
                            Id = 3,
                            Expiration = new DateTime(2025, 7, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = true,
                            Uuid = "33333333-3333-3333-3333-333333333333"
                        },
                        new
                        {
                            Id = 4,
                            Expiration = new DateTime(2025, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false,
                            Uuid = "44444444-4444-4444-4444-444444444444"
                        },
                        new
                        {
                            Id = 5,
                            Expiration = new DateTime(2025, 7, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IsUsed = false,
                            Uuid = "55555555-5555-5555-5555-555555555555"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@entreprise.com",
                            Name = "Alice Accueil",
                            Role = "Agent d'accueil"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@entreprise.com",
                            Name = "Bob Collaborateur",
                            Role = "Personnel"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@entreprise.com",
                            Name = "Charlie IT",
                            Role = "Administrateur"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactStaffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactStaffId = 1,
                            Email = "alexandre@example.com",
                            FirstName = "Alexandre",
                            LastName = "Lejunior",
                            Phone = "0123456789",
                            Status = "Enregistré",
                            VisitReason = "Rendez-vous"
                        },
                        new
                        {
                            Id = 2,
                            ContactStaffId = 2,
                            Email = "elodie@example.com",
                            FirstName = "Élodie",
                            LastName = "Martin",
                            Phone = "0987654321",
                            Status = "Enregistré",
                            VisitReason = "Coworking"
                        },
                        new
                        {
                            Id = 3,
                            ContactStaffId = 1,
                            Email = "paul@example.com",
                            FirstName = "Paul",
                            LastName = "Dupont",
                            Phone = "0147852369",
                            Status = "Enregistré",
                            VisitReason = "Coworking"
                        },
                        new
                        {
                            Id = 4,
                            ContactStaffId = 3,
                            Email = "sophie@example.com",
                            FirstName = "Sophie",
                            LastName = "Durand",
                            Phone = "0172638495",
                            Status = "Enregistré",
                            VisitReason = "Rendez-vous"
                        },
                        new
                        {
                            Id = 5,
                            ContactStaffId = 2,
                            Email = "julien@example.com",
                            FirstName = "Julien",
                            LastName = "Moreau",
                            Phone = "0192837465",
                            Status = "Enregistré",
                            VisitReason = "Rendez-vous"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Appointment", b =>
                {
                    b.HasOne("Reservation.Models.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation.Models.Visitor", "Visitor")
                        .WithMany("Appointments")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Reservation.Models.Staff", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Reservation.Models.Visitor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
